### PR TITLE
11 fix work

### LINKED ISSUE #11: waffle & sonar integration
Sonar, at least sonar maven plugin has issues with # in branch names. Let's see how both behave with GH- syntax to reference issues.

### PR DESCRIPTION
**Pull request by dadrus**
closes #11

### CODE REVIEW

File: src/main/java/com/github/dadrus/App.java [hunk 1]
```diff
@@ -6,12 +6,17 @@
...
 {
+	public static final String PASSWORD="boo";
     public static void main( String[] args )
     {
         System.out.println( "Hello World!" );
     }
 	
 	public void test() throws Exception {
-		
+		if(true) { // sonar doesn't like this comment style
```
Comment (dadrus) [inline src/main/java/com/github/dadrus/App.java]: MAJOR Change this condition so that it does not always evaluate to "true" [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2583)

File: src/main/java/com/github/dadrus/App.java [hunk 2]
```diff
@@ -6,12 +6,17 @@
...
+			throw new Exception("this"); // and the raw exception anyway
```
Comment (dadrus) [inline src/main/java/com/github/dadrus/App.java]: MAJOR Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00112)

File: src/main/java/com/github/dadrus/App.java [hunk 3]
```diff
@@ -6,12 +6,17 @@
...
+		} else {
+			throw new Exception("that");
```
Comment (dadrus) [inline src/main/java/com/github/dadrus/App.java]: MAJOR Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00112)

File: src/main/java/com/github/dadrus/App.java [hunk 4]
```diff
@@ -6,12 +6,17 @@
  */
 public class App 
 {
+	public static final String PASSWORD="boo";
```
Comment (dadrus) [inline src/main/java/com/github/dadrus/App.java]: BLOCKER Remove this hard-coded password. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2068)

**Comment by dadrus** [comment]
SonarQube analysis reported 4 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![MAJOR][MAJOR] 3 major

Watch the comments in this conversation to review them.

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by dadrus** [comment]
as expected a lot of sonar alerts. Let's fix them

**Comment by dadrus** [comment]
👎

**Comment by dadrus** [comment]
👍 Looks good now
